# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Abdullah Khaled's Engineering Portfolio"
email: abdullahkhaled0224@gmail.com
description: "Projects from school, robotics, internships, and personal work"
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://squirrr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  squirrr
linkedin_username: abdullah-khaled
youtube_username: abdullahkhaled

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Minimal Mistakes theme settings
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Author
author:
  name: "Abdullah Khaled"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Sophomore at Wakeland High School | Software Lead at Itkan Robotics | Engineering Enthusiast"
  location: "Frisco, TX"
  email: "abdullahkhaled0224@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:abdullahkhaled0224@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/squirrr"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/abdullah-khaled"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://youtube.com/@abdullahkhaled"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:abdullahkhaled0224@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/squirrr"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/abdullah-khaled"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://youtube.com/@abdullahkhaled"

# Site Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "PLTW Engineering"
    url: "/pltw-engineering/"
    children:
      - title: "Intro to Engineering Design"
        url: "/pltw-engineering/intro-to-engineering-design/"
      - title: "Principles of Engineering"
        url: "/pltw-engineering/principles-of-engineering/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
